### PR TITLE
Fix compilation with upcoming LaTeX2e release

### LINKED ISSUE #29: I think (?) EuropeCV will fail when new LaTeX2e is released
Thank you very much for your work on this package, Giuseppe, and for taking over after Nicola's work!

First, I should say I don't know much about LaTeX, so my notes below could be incorrect.

LaTeX2e is [going to release](https://www.latex-project.org//news/2022/05/27/latex-dev-2022-2/) a new version in a few days. TeX Live kindly provides a way to easily test the upcoming release: instead of using `pdflatex` (or friends), we can use `pdflatex-dev`. The following simple example succeeds when using `pdflatex` but fails with `pdflatex-dev` on an updated TeX Live 2022 system:

```
\documentclass[nologo]{europecv}

\begin{document}

\begin{europecv}{}

\ecvpersonalinfo{}{}

\end{europecv}{}

\end{document}
```

Here is the log file: [mwe.log](https://github.com/gsilano/EuropeCV/files/8824585/mwe.log)

From what I understand, this might be happening because europecv.cls uses `\RequirePackage{hyperref}` inside `\AtBeginDocument`. It is suggested [here](https://github.com/latex3/hyperref/issues/242#issuecomment-1144116033) that:

> In general it's a bad idea, hence dangerous, to load any package with \AtBeginDocument. Whether such use case works or not totally depends on the implementation of package and I doubt if it's ever officially supported.

As for why this is an issue only with the upcoming release and not the current release, I'm not sure but it might be described by the [most recent](https://www.latex-project.org/news/latex2e-news/ltnews35.pdf) LaTeX News issue (see the part about "Fixed bug when setting hook rules for one-time hooks").

### PR DESCRIPTION
**Pull request by scottkosty**
This commit fixes #29.

Notes:

1. There is a line at the top of the file templates/cv_template_en_bieber.tex:

  \def\Umathchar{} %prevents europecv to load utf8x

I don't understand the line but I wonder if it's still needed after this change?

2. Can you also double-check that it's appropriate that I removed the footnote in europecv.tex ?

3. Unfortunately I think the following minimal example will now fail on newer (i.e., releases with this commit) EuropeCV versions, although it compiled successfully with previous EuropeCV versions:

```
\documentclass[nologo]{europecv}
% this is the line that causes problems with the new (i.e., with this commit) EuropeCV version.
\usepackage[utf8x]{inputenc}

\begin{document}

\begin{europecv}{}

\ecvpersonalinfo{}{}

\end{europecv}{}

\end{document}
```

From what I understand (https://github.com/latex3/hyperref/issues/242#issuecomment-1146867828), it is recommended that the user moves away from utf8x. I mention this in the commit message and change log.

### CODE REVIEW

**Comment by gsilano** [comment]
Hi @scottkosty! I took a look at your changes. They didn't work for me. My TeX distribution encountered the error `Undefined control sequence. \AddToHook`. So, I reverted your changes back to the `europecv.cls` file. Please check that everything works for you with my changes. For convenience, I have already managed to add the new dates in the files ( **June 21, 2022**). This will save me time preparing for the release for CTAN and on GitHub. Please let me know if I can move on.

**Comment by scottkosty** [comment]
@gsilano thank you for finding the time to review and test it! Indeed, `\AddToHook` requires a new (any release in the past 2 years I believe) LaTeX version. Can you confirm the LaTeX release you're using is older than 2 years?

There might be a way to condition on LaTeX version (e.g., use `\AtBeginDocument` for older versions and `\AddToHook` for newer versions) but (1) that's beyond my LaTeX skills and (2) I'm not sure you would want to introduce that complexity to the code anyway.

I think there are two options:

1. Make the breaking change, and state that a LaTeX release in the last two years is required (I can figure out the exact release if you want).

2. Don't make the change.

We should think about what type of users download the newest version of EuropeCV. My guess is that mostly people with recent LaTeX releases install the newest versions of packages. But I don't have experience with this so I could be wrong.

**Comment by gsilano** [comment]
No, mine is a new version of LaTeX (installed a few days ago, on the new PC). Anyway, if `\AtBeginDocument` doesn't cause incompatibility issues with the new version of LaTeX, I would keep it as is. So, I can add some text to the manual for the latest version (i.e., the possibility to replace `\AtBeginDocument` with `\AddToHook`). If there are no other changes to be made, I will update the dates and the manual, then send the contribution to CTAN. Just let me know.

**Comment by TaaTT4** [comment]
I can confirm that also on my side it works with `\AtBeginDocument`. The issues I had was only related to the `ucs` and `inputenc` (with `utf8x` option) packages.

This is the LaTeX version that I'm using:
```
PS C:\Users\TaaTT4> pdflatex.exe --version
MiKTeX-pdfTeX 4.10 (MiKTeX 22.3)
© 1982 D. E. Knuth, © 1996-2021 Hàn Thế Thành
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.8, 13-Jul-2019
compiled with curl version 7.72.0; using libcurl/7.72.0 Schannel
compiled with expat version 2.2.10; using expat_2.2.10
compiled with jpeg version 9.4
compiled with liblzma version 50020052; using 50020052
compiled with libpng version 1.6.37; using 1.6.37
compiled with libressl version LibreSSL 3.1.4; using LibreSSL 3.1.4
compiled with MiKTeX Application Framework version 4.4; using 4.4
compiled with MiKTeX Core version 4.12; using 4.12
compiled with MiKTeX Archive Extractor version 4.0; using 4.0
compiled with MiKTeX Package Manager version 4.7; using 4.7
compiled with uriparser version 0.9.4
compiled with xpdf version 4.02
compiled with zlib version 1.2.11; using 1.2.11
```

**Comment by scottkosty** [comment]
> No, mine is a new version of LaTeX (installed a few days ago, on the new PC).

Good to know. This means my diagnosis was wrong. Indeed there must be a problem with my patch. I will check if I can figure it out.

> Anyway, if `\AtBeginDocument` doesn't cause incompatibility issues with the new version of LaTeX, I would keep it as is. So, I can add some text to the manual for the latest version (i.e., the possibility to replace `\AtBeginDocument` with `\AddToHook`). If there are no other changes to be made, I will update the dates and the manual, then send the contribution to CTAN. Just let me know.

Sounds good. I will test tomorrow and let you know.

**Comment by scottkosty** [comment]
> I can confirm that also on my side it works with `\AtBeginDocument`. The issues I had was only related to the `ucs` and `inputenc` (with `utf8x` option) packages.

Thanks for this information, TaaTT4. To make sure I understand, you are confirming that the current pull request (i.e., with Giuseppe's commit) works well for you, right?

**Comment by TaaTT4** [comment]
> Thanks for this information, TaaTT4. To make sure I understand, you are confirming that the current pull request (i.e., with Giuseppe's commit) works well for you, right?

Yes, exactly.

**Comment by scottkosty** [comment]
> > Anyway, if `\AtBeginDocument` doesn't cause incompatibility issues with the new version of LaTeX, I would keep it as is. So, I can add some text to the manual for the latest version (i.e., the possibility to replace `\AtBeginDocument` with `\AddToHook`). If there are no other changes to be made, I will update the dates and the manual, then send the contribution to CTAN. Just let me know.
> 
> Sounds good. I will test tomorrow and let you know.

With the second commit I get an error with the newest LaTeX release. Here is my log file: 
[mwe.log](https://github.com/gsilano/EuropeCV/files/8924200/mwe.log)

Unfortunately, it seems that neither of our commits works for everyone.

By the way, the new LaTeX 2e version [was released](https://www.latex-project.org/news/2022/06/14/issue35-of-latex2e-released/) on 14 June. If you use TeX Live I think all you have to do is do an update with tlmgr. I'm not sure how long it takes for the new release to make it to MiKTeX and others.

What TeX distribution do you use? What LaTeX 2e version is it? The key lines in my log file with the version info is here:

```
LaTeX2e <2022-06-01> pre-release-0 (develop 2022-6-16 branch)
L3 programming layer <2022-06-02>
```

As for what you should do, I don't know since nothing works for all of us. You might be able to condition on whether `\AddToHook` exists, and if so use it and if not use `\AtBeginDocument`. Perhaps the following is useful: https://tex.stackexchange.com/a/198590. Unfortunately I don't have the time to look into this possible approach.

<blockquote><div>TeX - LaTeX Stack Exchange</div><div><strong><a href="https://tex.stackexchange.com/questions/198586/conditional-based-on-the-version-of-pdflatex">Conditional based on the version of pdflatex?</a></strong></div><div>I would like to do this:

\pdfsuppresswarningpagegroup=1
However, this feature is only supported by pdftex 1.40.15 and higher. How can I do this conditionally, so that my document won't be broken in </div></blockquote>

**Comment by gsilano** [comment]
I think there are two separate issues. The first was about using `inputenc`, the second was for` \AtBeginningDocument` and `\AddToHook`. The former should be fixed, the latter is still ongoing. If you agree with me, I would release them separately as most of the EuropeCV's users do not plan to switch from LaTeX to LaTex 2e any time soon. Also, I should figure out how to release a package that might be compatible with both versions.

I will now make the package release compliant on CTAN.

**Comment by scottkosty** [comment]
I think that makes sense. Indeed at least the current version works for you and [TaaTT4](https://github.com/TaaTT4). Thanks for your time on this issue!

**Comment by MonsieurBon** [comment]
Will this issue be fixed soon? There is an open PR for this, can it be merged and released?

**Comment by gsilano** [comment]
Hi @MonsieurBon! Thank you for revisiting this topic. By reviewing this thread, I noticed that some of the changes were already merged into the `origin` with commit [fe91334](https://github.com/gsilano/EuropeCV/commit/fe913349093d2e2f5b9867c25c61a1dbcf1570ed). However, what follows on August 3, 2022, with #33, remains open. I'm curious if @vlasakm had the opportunity to further investigate this issue.

**Pull request merged**
