### PR TITLE
Add 'nobranding' option to hide 'Europass' branding

### PR DESCRIPTION
**Pull request by mahermanns**
The term *Europass* in the title may spark some confusion with people not familiar with this template. Similar to the *nologo* option, I added the *nobranding* option to the class to hide the term from the title if desired.

### CODE REVIEW

**Comment by gsilano** [comment]
I agree with you, but this change may raise some incompatibility issues. I mean, people who already use the LaTeX package and know nothing about the TeX code (i.e., the cls and def files), may no longer be able to compile their code, their CV, if they download the latest version I'm going to approve. Perhaps, at least for some future versions, it would be better to keep both the previous version and the new one, building the examples using the new version. In this way, new users will learn how to use the package using the new names, while other people will have to decide about their TeX: if they are interested in updating the CV to use the new features, or staying at an old version of the repository that better reflects their needs.

If you agree with my requests, please implement the necessary changes so that I can then approve them for later posting on CTAN.

**Comment by mahermanns** [comment]
@gsilano Sorry that I lost track on this issue. Coming back to it, I am not quite sure which backward incompatibilities should arise, as the default behavior should be the same. That is, old CVs should compile without problems. Just by adding the `nobranding` option, the new behavior gets activated.

At least that's how I intended it (or would). Could you point me which changes specifically you suspect (or know) to be problematic? I'd be happy to adapt.

**Comment by gsilano** [comment]
Hi @mahermanns! Don't worry, I know how much it can be complicated to stay tuned on these sort of things when you are involved in everyday working activities. Anyway, I just downloaded your changes and tried to test them before publishing a new software release of the package. Unfortunately, I did not understand what is exactly the improvement that you are proposing. Could you give an example of this? It could also help other users (seeing your example, they could understand its effectiveness).

Finally, could you follow what is described in the REAMDE.md and CONTRIBUNG.md files? It would make my work easier (release the new version on CTAN).

Thanks a lot for your contribution and for the help you gave me to make EuropeCV bigger.

Do not hesitate to correct my files (e.g., the README), if you find some parts that do not really make sense.

**Comment by mahermanns** [comment]
The option turns off the 'Europass' branding text. In the current version of the CV one can turn the logo on and off, but the 'Europass' branding text is hardcoded into the language files. My change makes this branding text disappear when the option is given.

Background is that I like the Europass CV layout for its clarity and style, yet not everyone is familiar with the term Europass and this sparked questions in the past when I showed the original CV to friends.

I will have a look into the README.md and CONTRIBUTING.md.

**Comment by gsilano** [comment]
I will help you to manage the pull request. Starting from the first week of December, I will work on it.

**Review by gsilano — APPROVED** [review]
The new feature is ready to be released

**Pull request merged**
